open(path ,mode)
data = open("junk.txt")
lines = data.readlines()
print(line[0:-1])
data.close()
with open ("Junk.text", "r") as data:
    lines = data.readlines()
    for line in lines 
    print (line[0:-1])
    with open ("junk.text","a") as file:
        file.write ("line 1\n")
        file.write ("line2 2\n")
        with open ("junk.text" 'w') as file:
            file.write ("Hello World \n")
            file.write ("Hello World2 \n")
            infile = open ("demo.txt" "r")
            demo = []
            for line in infile:
                data = line.splite ( ' ')
                demo.append(demo)
                print(My (demo))
                infile.close()  
            